services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel/config.yml"]
    volumes:
      - ./observability/otel-collector.yml:/etc/otel/config.yml
    ports:
      - "4318:4318"
      - "4319:4319"
    depends_on:
      - tempo
      - loki

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./observability/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    command: ["-config.file=/etc/tempo.yml"]
    volumes:
      - ./observability/tempo.yml:/etc/tempo.yml
    ports:
      - "3200:3200"
      - "4317:4317"

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    ports:
      - "3005:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
      - tempo

volumes:
  postgres-data:
  grafana-storage:

networks:
  vortex-network:
    driver: bridge
