services:
  api-gateway:
    image: oberdanandrade/vortex-api-gateway:latest
    container_name: api-gateway
    restart: always
    ports:
      - "3000:3000"
    env_file: .env

  products-service:
    image: oberdanandrade/vortex-products:latest
    container_name: products-service
    restart: always
    env_file: .env
    ports:
      - "4000:3000"

  users-service:
    image: oberdanandrade/vortex-users:latest
    container_name: users-service
    restart: always
    env_file: .env
    ports:
      - "4001:3000"

  auth-service:
    image: oberdanandrade/vortex-auth:latest
    container_name: auth-service
    restart: always
    env_file: .env
    ports:
      - "4002:3000"

networks:
  default:
    name: vortex-network
    driver: bridge